const fs=require('node:fs/promises'),path=require('node:path');
const pages=[
 {folder:'01-free-book',name:'Free book',slug:'freebestsellingbook',price:'$0 book + $9 postage',native:true,next:'discoverycallwithlloyd'},
 {folder:'02-discovery-call',name:'Free discovery call',slug:'discoverycallwithlloyd',price:'Complimentary',native:false,next:'suprisegift'},
 {folder:'03-surprise-gift',name:'Surprise gift',slug:'suprisegift',price:'$7 gift bundle',native:true,next:'strategycallwithlloyd'},
 {folder:'04-strategy-session',name:'Strategy session',slug:'strategycallwithlloyd',price:'$1,697 AUD',native:true,next:'congratulations-page'},
 {folder:'05-congratulations',name:'Congratulations',slug:'congratulations-page',price:'Confirmation page',native:false,next:null}
];
const nativeNotes={
 '01-free-book':'Attach the one-book offer and its $9 postage charge. Add the Property Intelligence Guide as an optional bump only after its price is confirmed. Leave the bump unchecked. Require contact and shipping details. Configure the receipt, printed-book fulfilment and PDF delivery workflow.',
 '03-surprise-gift':'Attach the $7 Positively Geared + Buy Now gift bundle. Require the recipient’s delivery address. Confirm and disclose any additional delivery/tax charge before payment. Configure gift fulfilment.',
 '04-strategy-session':'Attach the $1,697 Your Next Move service. Collect contact details; shipping is not needed for this service. Configure the receipt and session-coordination workflow.'
};
const domain='https://www.auspropertyprofessionals-invest.com.au';
function portable(code){for(const p of pages)code=code.replaceAll('href="'+domain+'/'+p.slug+'"','href="/'+p.slug+'"');return code;}
async function main(){
 const info=JSON.parse(await fs.readFile(path.join(__dirname,'paths.json'),'utf8'));const root=path.resolve(__dirname,info.output),out=path.join(root,'GHL-READY');await fs.mkdir(out,{recursive:true});
 const checkout=await fs.readFile(path.join(root,'GHL-NATIVE-CHECKOUT.css'),'utf8');await fs.writeFile(path.join(out,'NATIVE-CHECKOUT-STYLES.css'),checkout);
 const bundle=[];
 for(const p of pages){const dest=path.join(out,p.folder);await fs.mkdir(dest,{recursive:true});const parts=[];
  for(const [source,file,label]of p.native?[
   ['GHL-before-checkout.html','01-PASTE-ABOVE-CHECKOUT.html','Code block above the checkout'],
   ['GHL-after-checkout.html','03-PASTE-BELOW-CHECKOUT.html','Code block below the checkout']
  ]:[['GHL.html','01-PASTE-PAGE-CODE.html','Complete page code']]){
   const code=portable(await fs.readFile(path.join(root,p.folder,source),'utf8'));await fs.writeFile(path.join(dest,file),code);parts.push({file,label,code});
  }
  const instructions=`# ${p.name} — GHL placement\n\nPublished page path: /${p.slug}\n\nCreate this as a funnel step under Sites → Funnels. Use full-width sections and one-column rows. Turn on Allow Rows to Take Entire Width where available, and set section, row, column and code-element padding/margins to 0. Use #ffffff as the page background.\n\n${p.native?`1. Add a Custom HTML/JavaScript element and paste 01-PASTE-ABOVE-CHECKOUT.html.\n2. Add a separate native GHL One Step Order or Two Step Order element below it. Use a yellow #ffca05 section with 24px bottom padding, and a centred row up to 760px wide. Keep the order form itself white.\n3. Add another Custom HTML/JavaScript element and paste 03-PASTE-BELOW-CHECKOUT.html.\n4. Attach products/prices to this funnel step in its Products tab, and connect the payment gateway.\n5. Configure the native form’s successful-payment action to the next page: /${p.next}. A button click alone must not trigger the next paid step.\n\n${nativeNotes[p.folder]}\n\nOptional styling: assign pg-native-checkout to the native checkout container and paste ../NATIVE-CHECKOUT-STYLES.css into the page’s Custom CSS setting. This CSS contains no style tags.`:`1. Add one Custom HTML/JavaScript element and paste 01-PASTE-PAGE-CODE.html.\n2. Save and use Preview to check the code.\n\n${p.folder==='02-discovery-call'?'The existing Calendly discovery calendar is already embedded. The page shows a Continue link to the gift step and supports skipping the optional call. This does not configure a native GHL Calendar workflow.':'This page does not guess whether a visitor purchased or booked. Order receipts and calendar invitations are issued by the connected checkout/calendar.'}`}\n\nAll internal step links in these kit files use the paths above on the current domain. To use different paths or full URLs, set them in ../START-HERE.html and use its Copy code buttons. Test navigation on your published or staging funnel domain; GHL editor preview URLs can differ.\n\nThese are HTML fragments, not complete HTML documents. Do not paste index.html from the preview folders. Do not iframe the whole page. Paste each complete fragment into its own code element. Styles and scripts are included in each fragment; do not also duplicate them in Tracking Code.\n\nCode is ready to paste. The live GHL account, checkout, products and fulfilment must be configured and tested before launch.\n`;
  await fs.writeFile(path.join(dest,'SETUP.md'),instructions);
  if(p.native)await fs.writeFile(path.join(dest,'02-ADD-NATIVE-ORDER-FORM.txt'),nativeNotes[p.folder]+'\n\nThis is an instruction, not code to paste. Add the native GHL order form between files 01 and 03. See SETUP.md.\n');
  bundle.push({...p,parts,note:nativeNotes[p.folder]||''});
 }
 const readme=`# GHL-ready code kit\n\nOpen **START-HERE.html** for a copy-and-paste installer. It includes all five pages, editable destination URLs, code copy buttons and native checkout placement. It works locally without a server.\n\nThis is a set of Custom HTML/JavaScript snippets. The ZIP is only a convenient delivery package to extract on your computer; it is not a HighLevel snapshot or an importable native funnel. HighLevel’s funnel import feature imports existing HighLevel pages and does not turn an arbitrary HTML file into a native drag-and-drop page. Text and layout inside these custom blocks are edited in code.\n\n## Page mapping\n\n| Folder | Paste sequence | Published path |\n|---|---|---|\n${pages.map(p=>`| ${p.folder} | ${p.native?'01 code → native order form → 03 code':'01 complete page code'} | /${p.slug} |`).join('\n')}\n\n## What is included\n\n- Only deployment snippets and installation instructions; no demo form or preview navigation in the page code.\n- White and book-yellow backgrounds, responsive layouts, GitHub image URLs, embedded videos, media/award animation and accessible reduced-motion behaviour.\n- Complete, scoped HTML/CSS/JavaScript fragments without outer html, head or body tags.\n- Existing Calendly booking embed on the discovery page.\n- Relative step links for portability; the installer can substitute your chosen paths or full HTTPS URLs.\n\n## Remaining GHL setup\n\nAttach products, prices and the payment provider; add three native order forms; set order-success redirects and fulfilment. Confirm the guide’s bump price before enabling it. The existing secondary video introductions still show the old two-book offer and need revision for the one-book campaign. No code in this package takes card payments, creates orders, submits contacts or books appointments by itself.\n\n## Validation\n\nFragments checked for balanced container boundaries, scoped styles, script syntax, duplicate IDs, hosted image references, local-file references, and preview-only UI. Final account-specific rendering and test-mode purchases require the GHL builder and connected payment account.\n\n## Official HighLevel references\n\n- [Funnel/page import scope](https://help.gohighlevel.com/support/solutions/articles/48001209319-converting-funnels-and-websites-with-the-new-import-feature)\n- [Two-step checkout, products and order bumps](https://help.gohighlevel.com/support/solutions/articles/48000980307)\n- [Custom-code rendering troubleshooting](https://help.gohighlevel.com/support/solutions/articles/155000004983)\n`;
 await fs.writeFile(path.join(out,'README.md'),readme);
 await fs.writeFile(path.join(out,'START-HERE.html'),installer(bundle,checkout));
 await fs.writeFile(path.join(out,'funnel-map.json'),JSON.stringify(pages,null,2));
 console.log(JSON.stringify({kit:out,pages:bundle.length,codeFiles:bundle.reduce((n,p)=>n+p.parts.length,0)},null,2));
}
function installer(pages,checkout){const data=JSON.stringify({pages,checkout}).replace(/</g,'\\u003c');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Positively Geared — GHL installation kit</title><style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#211e20;font:15px/1.6 Arial,sans-serif}header{background:#ffca05;padding:40px max(24px,calc((100vw - 1120px)/2))}h1{font-size:clamp(30px,4vw,45px);line-height:1.1;margin:10px 0 18px}h2{font-size:25px;line-height:1.2}p{max-width:850px}main{max-width:1168px;padding:30px 24px 60px;margin:auto}small{letter-spacing:.08em}button,select,input,textarea{font:inherit}button{cursor:pointer;border:1px solid #211e20;border-radius:4px;background:#ffca05;color:#211e20;padding:11px 17px;font-weight:700}button:hover{background:white}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #211e20;outline-offset:3px}.notice{padding:18px 22px;border:1px solid #211e20;border-left:7px solid #ffca05;border-radius:4px;margin:22px 0}.url-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.url-grid label{font-weight:700;font-size:13px}.url-grid input{width:100%;padding:10px;margin-top:5px;border:1px solid #8c8882;border-radius:4px}.page-picker{display:flex;align-items:center;gap:20px;margin:30px 0 15px;border-top:1px solid #211e2026;padding-top:25px}.page-picker select{padding:12px;border:1px solid #211e20;max-width:100%;background:#fff}.part{border:1px solid #211e2030;border-radius:5px;padding:22px;margin-top:18px}.part h3{margin-top:0}.native{background:#ffca05;border-color:#211e20}.actions{display:flex;gap:14px;align-items:center;flex-wrap:wrap}textarea{width:100%;height:230px;resize:vertical;font:12px/1.5 monospace;padding:14px;background:#fff;border:1px solid #211e20;margin-top:15px}.status{min-height:26px;margin:12px 0;font-weight:700}.path{font-family:monospace;font-weight:400;overflow-wrap:anywhere}a{color:inherit}details{margin-top:15px}summary{cursor:pointer}li+li{margin-top:9px}@media(max-width:650px){.url-grid{grid-template-columns:1fr}.page-picker{display:block}.page-picker select{width:100%;margin-top:8px}}
</style></head><body><header><small>AUS PROPERTY PROFESSIONALS · POSITIVELY GEARED</small><h1>Your GHL installation kit.</h1><p>Five pages, with the exact code to paste into GoHighLevel. Use the existing white and book-yellow designs with GHL’s native checkout elements.</p></header><main>
<div class="notice"><strong>Ready to paste into Custom HTML/JavaScript elements.</strong><br>This is not a GHL snapshot or a direct HTML-file import. The three payment pages need native GHL order forms, attached products and a connected payment gateway.</div>
<h2>1. Set your five page destinations.</h2><p>These paths work on the same published domain. Change them if your new funnel uses different paths, or enter full HTTPS URLs. The copy buttons apply your current values to the code. Refreshing this installer resets these fields.</p><div class="url-grid" id="urls"></div>
<h2>2. Create the funnel steps in GHL.</h2><p>Under Sites → Funnels, add five steps. In each builder, use a full-width section, allow rows to take the full width, and set the section, row, column and code-element padding/margins to zero. Set the page background to white. Paste the blocks below in the shown order, save, and use Preview.</p>
<div class="page-picker"><label for="page"><strong>3. Choose a page:</strong></label><select id="page"></select></div><div id="panel"></div><p class="status" id="status" role="status" aria-live="polite"></p>
<div class="notice"><strong>Before launch:</strong> configure native checkout products, payment-success redirects, receipts and fulfilment. Confirm the guide’s bump price. Update the legacy secondary video introductions for the one-book offer. Run test-mode orders in GHL.</div><p><a href="README.md">Full setup notes</a> · <a href="https://help.gohighlevel.com/support/solutions/articles/48000980307" target="_blank" rel="noopener">Official GHL order-form guide ↗</a></p></main>
<script type="application/json" id="kit-data">${data}</script><script>
(function(){'use strict';var kit=JSON.parse(document.getElementById('kit-data').textContent),choice=document.getElementById('page'),panel=document.getElementById('panel'),status=document.getElementById('status');
function el(tag,text,cls){var e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
kit.pages.forEach(function(p,i){var label=el('label',(i+1)+'. '+p.name),input=el('input');input.id='url-'+i;input.value='/'+p.slug;input.setAttribute('aria-label',p.name+' destination');label.appendChild(input);document.getElementById('urls').appendChild(label);var option=el('option',(i+1)+'. '+p.name);option.value=i;choice.appendChild(option);input.addEventListener('input',render);});
function destinations(){return kit.pages.map(function(p,i){var value=document.getElementById('url-'+i).value.trim();if(!(value.startsWith('/')&&!value.startsWith('//'))&&!value.startsWith('https://'))throw Error('Use a /page-path or full https:// URL for '+p.name+'.');if(/[<>"\\s]/.test(value))throw Error('Remove spaces or quote characters from '+p.name+' destination.');return value.replace(/&/g,'&amp;');});}
function code(part){var targets=destinations();return part.code.replace(/href="([^"]+)"/g,function(match,href){var i=kit.pages.findIndex(function(p){return href==='/'+p.slug;});return i<0?match:'href="'+targets[i]+'"';});}
async function copy(text,textarea){try{await navigator.clipboard.writeText(text);status.textContent='Copied. Paste this into the specified GHL setting.';}catch(e){var t=textarea||el('textarea');var temporary=!textarea;if(temporary){t.value=text;document.body.appendChild(t);}var details=t.closest('details');if(details)details.open=true;t.focus();t.select();var ok=false;try{ok=document.execCommand('copy');}catch(ignore){}status.textContent=ok?'Copied. Paste this into the specified GHL setting.':'Code selected. Press Ctrl+C, then paste it into GHL.';if(temporary&&ok)t.remove();}}
function partCard(part){var card=el('section',null,'part');card.appendChild(el('h3',part.label));card.appendChild(el('p',part.file,'path'));var area=el('textarea');area.readOnly=true;area.setAttribute('aria-label',part.label+' source code');try{area.value=code(part);}catch(e){area.value=e.message;}var button=el('button','Copy this code');button.type='button';button.addEventListener('click',function(){try{var text=code(part);area.value=text;copy(text,area);}catch(e){status.textContent=e.message;}});card.appendChild(button);var details=el('details');details.appendChild(el('summary','View code / copy manually'));details.appendChild(area);card.appendChild(details);return card;}
function render(){var p=kit.pages[Number(choice.value)||0];panel.replaceChildren();status.textContent='';panel.appendChild(el('h2',p.name));panel.appendChild(el('p','Offer: '+p.price));panel.appendChild(partCard(p.parts[0]));if(p.native){var card=el('section',null,'part native');card.appendChild(el('h3','2. Add a native GHL order form here'));card.appendChild(el('p',p.note));card.appendChild(el('p','Use a yellow section, a centred row up to 760px wide, and a white form. Attach products in this step’s Products tab. Set the successful-payment action to the next page destination below.'));var next=kit.pages.findIndex(function(x){return x.slug===p.next;});card.appendChild(el('p','After successful payment: '+document.getElementById('url-'+next).value,'path'));card.appendChild(el('p','For optional styling, assign the class pg-native-checkout to the checkout container and paste the CSS into the page Custom CSS setting.'));var btn=el('button','Copy native checkout CSS');btn.type='button';btn.addEventListener('click',function(){copy(kit.checkout);});card.appendChild(btn);panel.appendChild(card);panel.appendChild(partCard(p.parts[1]));}else{panel.appendChild(el('p',p.folder==='02-discovery-call'?'The existing Calendly booking calendar is included. Check the calendar in Preview.':'This page needs only the single code block above.'));}}
choice.addEventListener('change',render);render();})();
</script></body></html>`;}
main().catch(e=>{console.error(e);process.exitCode=1;});
